### ISSUE TITLE
build fails on windows 7 x64 using 32 bit python 2.7 and MSVS 9.0

### ISSUE THREAD

**Issue by KenV99** [fancycode/pylzma#25]
using latest code from master, setup.py build fails as follows:

src/pylzma/pylzma.c(284) : error C2065: 'None' : undeclared identifier
src/pylzma/pylzma.c(284) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
src/pylzma/pylzma.c(284) : warning C4024: 'PyModule_AddStringConstant' : different types for formal and actual parameter 3
error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed with exit status 2

Any thoughts? Thanks for your work on this.

**Comment by GaryHendrick** [comment]
I just checked this out and received similar error 
Using : Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
See the build log here:
https://gist.github.com/GaryHendrick/67a85d65ab3b99404441

**Comment by fancycode** [comment]
Unfortunately I don't have a Windows machine available for testing, could you please check if the latest push fixed this issue for you?

**Comment by KenV99** [comment]
Thank you. The build succeeds now.

**Comment by GaryHendrick** [comment]
Confirmed, the build succeeds as of version 080ad8f of setup.py
