### ISSUE TITLE
Pylzma cannot decrypt encrypted headers from 7z

### ISSUE THREAD

**Issue by KenV99** [fancycode/pylzma#28]
If I include the `-mhe` switch to encrypt headers, I get an 'invalid block data error' from `Archive7z.__init__()` in py7zlib.py.

In what may be a side note, in `class Header.__init__()` in the line `self.properties = ArchiveProperties(file)`, `ArchiveProperties` is not defined in py7zlib.py.

Are encrypted headers not supported?
Thanks again for all of your help.

**Comment by fancycode** [comment]
I think this was just fixed together with #33. Please reopen if you still get the error (and provide a minimal sample archive).
