### ISSUE TITLE
gcc: error: unrecognized command line option '-mno-cygwin'  using WIN 7 and GCC 4.7

### ISSUE THREAD

**Issue by chfakht** [fancycode/pylzma#35]
Hi, i'm on WIN 7 64 bits i have used both CMD and cygwin terminal but i get this ERROR:
gcc: error: unrecognized command line option '-mno-cygwin'

gcc version is:
gcc version 4.7.4 20140401 for GNAT GPL gpl-2014 (20140405) (GCC)

thanks

**Comment by fancycode** [comment]
This is most likely added by your Python subsystem when compiling pylzma, so you should check there. The option is used nowhere in the setup scripts of pylzma.
