### ISSUE TITLE
Prepare a new release

### ISSUE THREAD

**Issue by vminakov** [fancycode/pylzma#45]
Hi,

just wanted to ask whether it is possible that you could prepare another release? There were quite some bugs fixed since last release, particularly #37 and #33. At the moment I have to wrap pylzma myself with back ported patches, but I believe current master is stable enough for the release. What do you think?

**Comment by fancycode** [comment]
Good idea, I will look into releasing a new version sometime the next days.

**Comment by maniax89** [comment]
any chance this could get revisited? was looking for the latest version to handle newer 7z formats (fixed by https://github.com/fancycode/pylzma/issues/37)

**Comment by fancycode** [comment]
Sorry, completely forgot about this.

Released as v0.4.9 now:
https://github.com/fancycode/pylzma/releases/tag/v0.4.9
https://pypi.python.org/pypi/pylzma/0.4.9
https://pypi.org/project/pylzma/0.4.9/
