### ISSUE TITLE
Unpacking AES-256 encrypted zip files in memory using pylzma

### ISSUE THREAD

**Issue by rkatriel-mdsol** [fancycode/pylzma#55]
Hi,

I am using the ZipFile module from the Python zipfile package to read in and unpack zip archives into memory:

    import zipfile
    zfile = zipfile.ZipFile(filehandle, 'r', compression=zipfile.ZIP_LZMA)
    zfile.setpassword(password)

However, this does not work with AES-256 encryption (a known issue). Is it possible to achieve this using pylzma?

Thanks,
Ron

**Comment by fancycode** [comment]
pylzma supports AES-256 encryption for `.7z` files, but not for `.zip` files.
