### ISSUE TITLE
py7zlib fails with `IndexError: list index out of range` when opening  specific 7z archive

### ISSUE THREAD

**Issue by miurahr** [fancycode/pylzma#59]
py7zlib caught out of range error when opening specific file.

## how to reproduce

Run snippet following

```python
#!/usr/bin/env python

import py7zlib
import requests

archive = 'testfile.7z'
url = 'https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_597/qt.qt5.597.gcc_64/5.9.7-0-201810181452qtxmlpatterns-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z'
r = requests.get(url, stream=True)
with open(archive, 'wb') as fd:
    for chunk in r.iter_content(chunk_size=512):
        fd.write(chunk)
f = py7zlib.Archive7z(open(archive, 'rb'))
```

## Traceback
```
 Traceback (most recent call last):
  File "./repro.py", line 13, in <module>
    f = py7zlib.Archive7z(open(archive, 'rb'))
  File "/home/miurahr/projects/qli-installer/venv/lib/python3.5/site-packages/py7zlib.py", line 884, n __init__
    folder = folders[fidx]
IndexError: list index out of range

```

## Version

pylzma-0.5.0.post0`

## related issues

#9 

## Environment

Linux Mint 18.3 (Sylvia), python 3.5.2

**Comment by miurahr** [comment]
The example file seems to be built with `-m0=LZMA2:d23` option, but it cannot be reproduced with another files. 
```
Type = 7z
Physical Size = 1161371
Headers Size = 5574
Method = LZMA2:23
Solid = +
Blocks = 1
```

**Comment by fancycode** [comment]
Could you please provide a small sample file containing only a "Hello world!" textfile?

**Comment by miurahr** [comment]
I cannot reproduce it with small files. It is a smallest file in which I observed same error.

The file has 418 files, 14 folders.
When run it with PyCharm debugger, I got 

* in line 884,
* fidx: 1
* len(folders): 1
* len(subinfo.unpackstreams): 1
* subinfo.unpackstreams[0]: 417
* info['filename'] = `5.9.7/gcc_64/lib/libQt5XmlPatterns.prl`  as same as  a last file shown when running `7zr l ` command that file size is 1088
* obidx: 417
* packsizes[0]: 1155797
* streams.packinfo.numstreams: 1
* streams.packinfo.packpos: 1155797
* streams.packinfo.packsizes[0]: 5505
* unpackinfo.folders[0].solid: False

It seems a problem may happen in last file in an archive.

**Comment by miurahr** [comment]
> Could you please provide a small sample file containing only a "Hello world!" textfile?

Trying test with "Hello World!" data pass a test.

```

    def test_github_59(self):
        fp = self._open_file(os.path.join(ROOT, 'data', 'github_59_small.7z'), 'rb')
        archive = Archive7z(fp)
        self._test_decode_all(archive)
```

**Comment by miurahr** [comment]
Generating random 418 files become no luck, too.

```python
import os
import random

os.mkdir('github_59')
for i in range(13):
    os.mkdir('github_59/dir%d' % i)
for i in range(418):
    with open('github_59/dir1/%d'% i, 'wb') as f:
        for j in range(random.randrange(1024)):
            f.write(random.randrange(65535).to_bytes(2, 'big'))
os.system('7z a -m0=LZMA2:d23 github_59_s.7z github_59/')
```

```
Path = github_59_s.7z
Type = 7z
Physical Size = 426246
Headers Size = 2991
Method = LZMA2:19
Solid = +
Blocks = 1
```

It is difficult to make a small file to reproduce the issue.

**Comment by fancycode** [comment]
> I cannot reproduce it with small files. It is a smallest file in which I observed same error.

Feel free to send me the file by mail, you can find the address in my profile.

**Comment by miurahr** [comment]
Could you  wget https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_597/qt.qt5.597.gcc_64/5.9.7-0-201810181452qtxmlpatterns-Linux-RHEL_7_4-GCC-Linux-RHEL_7_4-X86_64.7z

**Comment by kerwei** [comment]
@fancycode I just ran into the same issue at my end. I looked around a little bit and saw that commit [9122f07](https://github.com/fancycode/pylzma/commit/9122f07f71f5a5025cc06a3510f846aecc3a27a7) had failed build, while subsequent commits passed all the builds. As I am not familiar with the CI process, I am not sure if this means that the failed build was addressed by subsequent ones and therefore, the fix was still shipped eventually. However, a quick inspection of the commit and a comparison with the pypi release version 0.5 seems to indicate that changes from this commit were not eventually shipped.

**Comment by kerwei** [comment]
@fancycode Okay, nevermind. I just found out that released version 0.5.0 has the codebase from commit  [56a23b7](https://github.com/fancycode/pylzma/commit/56a23b7fa0a019dd24370389b541606f08aac944) from way back in Sept 2018. Are there any plans for newer releases?

**Comment by medoc92** [comment]
I have the same issue. pylzma 0.5.0 installed with pip3 on Ubuntu Focal:

````
 echo 'from py7zlib import Archive7z; fp = open("recoll.7z", "rb");a = Archive7z(fp)'  |  python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/py7zlib.py", line 884, in __init__
    folder = folders[fidx]
IndexError: list index out of range
````

The archive has source files for the open source project recoll in it. You can download it from: https://www.lesbonscomptes.com/recoll/files/recoll.7z

**Comment by miurahr** [comment]
@medoc92 you can see [alternative 7z library](https://github.com/miurahr/py7zr).

**Comment by medoc92** [comment]
@miurahr the problem is that I need to read the data to memory, and I get the impression that the py7zr memory only works for extracting to files ?

**Comment by miurahr** [comment]
@medoc92 you should put a question for another project, on that project.
