### ISSUE TITLE
Support for LZMA2

### ISSUE THREAD

**Issue by lkraider** [fancycode/pylzma#7]
There is an updated LZMA SDK (9.20), and has support for LZMA2, pylzma should be updated to support that.

**Comment by chfakht** [comment]
@lkraider  yes LZMA2 was developped in 2009 , LZMA is very old 1998

**Comment by encolpe** [comment]
Since Python 3.3 there is a [lzma implementation in the standard library](https://docs.python.org/3/library/lzma.html), and a backport for Python 2 with [backport.lzma](https://github.com/peterjc/backports.lzma). It can simplify your work :)
Both Python3 and Python2 still missing a good 7z support.

**Comment by fancycode** [comment]
LZMA support is finally happening in #51 (work in progress).
